apiVersion: v1
kind: ServiceAccount
metadata:
  name:  clusterlink-controller-manager
  namespace: clusterlink-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterlink-controller-manager
  namespace: clusterlink-system
  labels:
    app: clusterlink-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterlink-controller-manager
  template:
    metadata:
      labels:
        app: clusterlink-controller-manager
    spec:
      serviceAccountName: clusterlink-controller-manager
      containers:
        - name: manager
          image: ghcr.io/kosmos-io/clusterlink/clusterlink-controller-manager:__VERSION__
          imagePullPolicy: IfNotPresent
          command:
            - clusterlink-controller-manager
            - --controlpanelconfig=/etc/clusterlink/kubeconfig
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - mountPath: /etc/clusterlink
              name: proxy-config
              readOnly: true